"""initial ordering schema

Revision ID: 202608160001
Revises:
Create Date: 2026-08-16
"""

from alembic import op
import sqlalchemy as sa

revision = "202608160001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("users", sa.Column("id", sa.String(36), primary_key=True), sa.Column("email", sa.String(254), nullable=False, unique=True), sa.Column("display_name", sa.String(120), nullable=False), sa.Column("password_hash", sa.String(255), nullable=False), sa.Column("role", sa.String(16), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("restaurants", sa.Column("id", sa.String(36), primary_key=True), sa.Column("name", sa.String(160), nullable=False), sa.Column("is_configured", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("restaurant_settings", sa.Column("id", sa.String(36), primary_key=True), sa.Column("restaurant_id", sa.String(36), sa.ForeignKey("restaurants.id", ondelete="CASCADE"), nullable=False, unique=True), sa.Column("is_open", sa.Boolean(), nullable=False), sa.Column("pickup_enabled", sa.Boolean(), nullable=False), sa.Column("delivery_enabled", sa.Boolean(), nullable=False), sa.Column("delivery_fee_kobo", sa.Integer(), nullable=False), sa.Column("minimum_order_kobo", sa.Integer()), sa.Column("address", sa.String(255)), sa.Column("phone", sa.String(32)), sa.Column("hours_note", sa.String(255)), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("categories", sa.Column("id", sa.String(36), primary_key=True), sa.Column("restaurant_id", sa.String(36), sa.ForeignKey("restaurants.id", ondelete="CASCADE"), nullable=False), sa.Column("name", sa.String(100), nullable=False), sa.Column("sort_order", sa.Integer(), nullable=False), sa.Column("is_archived", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("menu_items", sa.Column("id", sa.String(36), primary_key=True), sa.Column("restaurant_id", sa.String(36), sa.ForeignKey("restaurants.id", ondelete="CASCADE"), nullable=False), sa.Column("category_id", sa.String(36), sa.ForeignKey("categories.id", ondelete="RESTRICT"), nullable=False), sa.Column("name", sa.String(160), nullable=False), sa.Column("description", sa.Text()), sa.Column("price_kobo", sa.Integer(), nullable=False), sa.Column("prep_minutes", sa.Integer()), sa.Column("is_available", sa.Boolean(), nullable=False), sa.Column("is_archived", sa.Boolean(), nullable=False), sa.Column("image_url", sa.String(1024)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("menu_item_options", sa.Column("id", sa.String(36), primary_key=True), sa.Column("menu_item_id", sa.String(36), sa.ForeignKey("menu_items.id", ondelete="CASCADE"), nullable=False), sa.Column("name", sa.String(120), nullable=False), sa.Column("price_delta_kobo", sa.Integer(), nullable=False), sa.Column("is_available", sa.Boolean(), nullable=False))
    op.create_table("addresses", sa.Column("id", sa.String(36), primary_key=True), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("label", sa.String(80), nullable=False), sa.Column("address_line", sa.String(255), nullable=False), sa.Column("landmark", sa.String(255)), sa.Column("phone", sa.String(32)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("orders", sa.Column("id", sa.String(36), primary_key=True), sa.Column("public_number", sa.String(32), nullable=False, unique=True), sa.Column("restaurant_id", sa.String(36), sa.ForeignKey("restaurants.id", ondelete="RESTRICT"), nullable=False), sa.Column("customer_id", sa.String(36), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("fulfillment_type", sa.String(16), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("payment_status", sa.String(32), nullable=False), sa.Column("customer_name", sa.String(120), nullable=False), sa.Column("customer_phone", sa.String(32), nullable=False), sa.Column("customer_email", sa.String(254)), sa.Column("delivery_address", sa.Text()), sa.Column("customer_note", sa.Text()), sa.Column("subtotal_kobo", sa.Integer(), nullable=False), sa.Column("delivery_fee_kobo", sa.Integer(), nullable=False), sa.Column("total_kobo", sa.Integer(), nullable=False), sa.Column("version", sa.Integer(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("accepted_at", sa.DateTime(timezone=True)), sa.Column("preparing_at", sa.DateTime(timezone=True)), sa.Column("ready_at", sa.DateTime(timezone=True)), sa.Column("dispatched_at", sa.DateTime(timezone=True)), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.Column("cancelled_at", sa.DateTime(timezone=True)))
    op.create_table("order_items", sa.Column("id", sa.String(36), primary_key=True), sa.Column("order_id", sa.String(36), sa.ForeignKey("orders.id", ondelete="CASCADE"), nullable=False), sa.Column("menu_item_id", sa.String(36), sa.ForeignKey("menu_items.id", ondelete="SET NULL")), sa.Column("name_snapshot", sa.String(160), nullable=False), sa.Column("unit_price_kobo", sa.Integer(), nullable=False), sa.Column("quantity", sa.Integer(), nullable=False), sa.Column("options_snapshot", sa.JSON(), nullable=False), sa.Column("special_instructions", sa.Text()))
    op.create_table("order_status_history", sa.Column("id", sa.String(36), primary_key=True), sa.Column("order_id", sa.String(36), sa.ForeignKey("orders.id", ondelete="CASCADE"), nullable=False), sa.Column("from_status", sa.String(32)), sa.Column("to_status", sa.String(32), nullable=False), sa.Column("actor_id", sa.String(36), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("note", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("payments", sa.Column("id", sa.String(36), primary_key=True), sa.Column("order_id", sa.String(36), sa.ForeignKey("orders.id", ondelete="CASCADE"), nullable=False), sa.Column("provider", sa.String(32), nullable=False), sa.Column("reference", sa.String(160), nullable=False, unique=True), sa.Column("amount_kobo", sa.Integer(), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("provider_response", sa.JSON()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("idempotency_keys", sa.Column("key", sa.String(160), primary_key=True), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("route", sa.String(160), nullable=False), sa.Column("response_code", sa.Integer(), nullable=False), sa.Column("response_body", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    for table, columns in {"categories": ["restaurant_id"], "menu_items": ["restaurant_id", "category_id"], "orders": ["restaurant_id", "customer_id", "status"], "order_items": ["order_id"], "order_status_history": ["order_id"], "payments": ["order_id"], "addresses": ["user_id"]}.items():
        for column in columns:
            op.create_index(f"ix_{table}_{column}", table, [column])


def downgrade() -> None:
    for table in ["idempotency_keys", "payments", "order_status_history", "order_items", "orders", "addresses", "menu_item_options", "menu_items", "categories", "restaurant_settings", "restaurants", "users"]:
        op.drop_table(table)
